# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='nomeend',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
